services:
  elasticsearch:
    image: elasticsearch:8.1.3
    restart: always
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'false'

  kibana:
    image: kibana:8.1.3
    ports:
      - 5601:5601
    restart: always
